# This file was generated by the {rix} R package v0.15.6 on 2025-03-14
# with following call:
# >rix(r_ver = "4.3.3",
#  > r_pkgs = c("BiocManager",
#  > "clusterProfiler",
#  > "org.Hs.eg.db",
#  > "miniUI",
#  > "pathview",
#  > "enrichplot",
#  > "biomaRt",
#  > "ggplot2",
#  > "ggrepel",
#  > "msigdbr",
#  > "ggnewscale",
#  > "ggridges",
#  > "tidyverse",
#  > "styler",
#  > "DESeq2",
#  > "tinytex"),
#  > system_pkgs = c("quarto"),
#  > git_pkgs = NULL,
#  > tex_pkgs = c("framed"),
#  > ide = "rstudio",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2024-02-29.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      BiocManager
      biomaRt
      clusterProfiler
      DESeq2
      enrichplot
      ggnewscale
      ggplot2
      ggrepel
      ggridges
      miniUI
      msigdbr
      org_Hs_eg_db
      pathview
      styler
      tidyverse
      tinytex;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      framed;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [  rpkgs  ];
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs tex system_packages  wrapped_pkgs ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
